[backend]
db_url = "postgres://postgres:postgres@postgres/postgres"
migrations = "/usr/share/hazel/migrations/"
storage = "/var/lib/hazel/storage/"

[web]
max_upload_filesize_mb = 999
resources = "/usr/share/hazel/resources/"

[server]
port = 8080

[auth]
superuser_password = "PleaseChangeThis"
open_for_registration = false
